# -*- coding: utf-8 -*-

"""
notionapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import os
import unittest
from tests.http_response_catcher import HttpResponseCatcher
from notionapi.configuration import Configuration, Environment
from notionapi.notionapi_client import NotionapiClient
from notionapi.http.auth.o_auth_2 import BearerAuthCredentials


class ControllerTestBase(unittest.TestCase):

    """All test classes inherit from this base class. It abstracts out
    common functionality and configuration variables set up."""

    client = None
    config = None

    @classmethod
    def setUpClass(cls):
        """Class method called once before running tests in a test class."""
        cls.request_timeout = 30
        cls.assert_precision = 0.01
        cls.config = ControllerTestBase.create_configuration()
        cls.client = NotionapiClient(config=cls.config)

    @staticmethod
    def create_configuration():
        environment = os.getenv('NOTIONAPI_ENVIRONMENT')
        access_token = os.getenv('NOTIONAPI_ACCESS_TOKEN')

        if environment is not None:
            environment = Environment[environment.upper()]
        bearer_auth_credentials=None
        if access_token is not None:
            bearer_auth_credentials=BearerAuthCredentials(
                access_token=access_token)


        config = Configuration(http_call_back=HttpResponseCatcher())
        return config.clone_with(
            bearer_auth_credentials=bearer_auth_credentials,
            environment=environment)

