# -*- coding: utf-8 -*-

"""
notionapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from notionapi.api_helper import APIHelper


class SearchControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(SearchControllerTests, cls).setUpClass()
        cls.controller = cls.client.search
        cls.response_catcher = cls.controller.http_call_back

    # Search
    def test_search(self):
        # Parameters for the API call
        notion_version = '{{NOTION_VERSION}}'
        body = None

        # Perform the API call through the SDK function
        result = self.controller.search(notion_version, body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['date'] = None
        expected_headers['transfer-encoding'] = None
        expected_headers['connection'] = None
        expected_headers['set-cookie'] = None
        expected_headers['x-dns-prefetch-control'] = None
        expected_headers['x-frame-options'] = None
        expected_headers['strict-transport-security'] = None
        expected_headers['x-download-options'] = None
        expected_headers['x-content-type-options'] = None
        expected_headers['x-xss-protection'] = None
        expected_headers['referrer-policy'] = None
        expected_headers['content-security-policy'] = None
        expected_headers['x-content-security-policy'] = None
        expected_headers['x-webkit-csp'] = None
        expected_headers['etag'] = None
        expected_headers['vary'] = None
        expected_headers['content-encoding'] = None
        expected_headers['cf-cache-status'] = None
        expected_headers['expect-ct'] = None
        expected_headers['server'] = None
        expected_headers['cf-ray'] = None
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"object":"list","results":[{"object":"page","id":"ae1905c3-b77b-4'
            '75b-b98f-7596c242137f","created_time":"2021-05-21T16:41:00.000Z","'
            'last_edited_time":"2021-05-21T16:41:00.000Z","created_by":{"object'
            '":"user","id":"92a680bb-6970-4726-952b-4f4c03bff617"},"last_edited'
            '_by":{"object":"user","id":"92a680bb-6970-4726-952b-4f4c03bff617"}'
            ',"cover":null,"icon":null,"parent":{"type":"database_id","database'
            '_id":"8e2c2b76-9e1d-47d2-87b9-ed3035d607ae"},"archived":false,"pro'
            'perties":{"Score /5":{"id":")Y7%22","type":"select","select":{"id"'
            ':"5c944de7-3f4b-4567-b3a1-fa2c71c540b6","name":"⭐️⭐️⭐️⭐️⭐️","color'
            '":"default"}},"Type":{"id":"%2F7eo","type":"select","select":{"id"'
            ':"f96d0d0a-5564-4a20-ab15-5f040d49759e","name":"Article","color":"'
            'default"}},"Publisher":{"id":"%3E%24Pb","type":"select","select":{'
            '"id":"01f82d08-aa1f-4884-a4e0-3bc32f909ec4","name":"The Atlantic",'
            '"color":"red"}},"Summary":{"id":"%3F%5C25","type":"rich_text","ric'
            'h_text":[{"type":"text","text":{"content":"Some think chief ethics'
            ' officers could help technology companies navigate political and s'
            'ocial questions.","link":null},"annotations":{"bold":true,"italic"'
            ':true,"strikethrough":true,"underline":true,"code":true,"color":"d'
            'efault"},"plain_text":"Some think chief ethics officers could help'
            ' technology companies navigate political and social questions.","h'
            'ref":null}]},"Publishing/Release Date":{"id":"%3Fex%2B","type":"da'
            'te","date":{"start":"2020-12-08T12:00:00.000+00:00","end":null,"ti'
            'me_zone":null}},"Link":{"id":"VVMi","type":"url","url":"https://ww'
            'w.nytimes.com/2018/10/21/opinion/who-will-teach-silicon-valley-to-'
            'be-ethical.html"},"Read":{"id":"_MWJ","type":"checkbox","checkbox"'
            ':false},"Status":{"id":"%60zz5","type":"select","select":{"id":"8c'
            '4a056e-6709-4dd1-ba58-d34d9480855a","name":"Ready to Start","color'
            '":"yellow"}},"Author":{"id":"qNw_","type":"multi_select","multi_se'
            'lect":[]},"Name":{"id":"title","type":"title","title":[{"type":"te'
            'xt","text":{"content":"New Media Article","link":null},"annotation'
            's":{"bold":false,"italic":false,"strikethrough":false,"underline":'
            'false,"code":false,"color":"default"},"plain_text":"New Media Arti'
            'cle","href":null}]}},"url":"https://www.notion.so/New-Media-Articl'
            'e-ae1905c3b77b475bb98f7596c242137f"},{"object":"page","id":"8f1606'
            '1d-4b77-4dbc-bf04-e8b0b4319b5a","created_time":"2021-05-21T16:42:0'
            '0.000Z","last_edited_time":"2021-05-21T16:42:00.000Z","created_by"'
            ':{"object":"user","id":"92a680bb-6970-4726-952b-4f4c03bff617"},"la'
            'st_edited_by":{"object":"user","id":"92a680bb-6970-4726-952b-4f4c0'
            '3bff617"},"cover":null,"icon":null,"parent":{"type":"database_id",'
            '"database_id":"7a94f22f-59ae-484d-90ac-4aeddd667641"},"archived":f'
            'alse,"properties":{"Score /5":{"id":")Y7%22","type":"select","sele'
            'ct":{"id":"5c944de7-3f4b-4567-b3a1-fa2c71c540b6","name":"⭐️⭐️⭐️⭐️⭐'
            '️","color":"default"}},"Type":{"id":"%2F7eo","type":"select","sele'
            'ct":{"id":"f96d0d0a-5564-4a20-ab15-5f040d49759e","name":"Article",'
            '"color":"default"}},"Publisher":{"id":"%3E%24Pb","type":"select","'
            'select":{"id":"01f82d08-aa1f-4884-a4e0-3bc32f909ec4","name":"The A'
            'tlantic","color":"red"}},"Summary":{"id":"%3F%5C25","type":"rich_t'
            'ext","rich_text":[{"type":"text","text":{"content":"Some think chi'
            'ef ethics officers could help technology companies navigate politi'
            'cal and social questions.","link":null},"annotations":{"bold":true'
            ',"italic":true,"strikethrough":true,"underline":true,"code":true,"'
            'color":"default"},"plain_text":"Some think chief ethics officers c'
            'ould help technology companies navigate political and social quest'
            'ions.","href":null}]},"Publishing/Release Date":{"id":"%3Fex%2B","'
            'type":"date","date":{"start":"2020-12-08T12:00:00.000+00:00","end"'
            ':null,"time_zone":null}},"date":{"id":"Lpwp","type":"date","date":'
            'null},"Link":{"id":"VVMi","type":"url","url":"https://www.nytimes.'
            'com/2018/10/21/opinion/who-will-teach-silicon-valley-to-be-ethical'
            '.html"},"Wine Pairing":{"id":"WO%40Z","type":"rich_text","rich_tex'
            't":[]},"Read":{"id":"_MWJ","type":"checkbox","checkbox":false},"St'
            'atus":{"id":"%60zz5","type":"select","select":{"id":"8c4a056e-6709'
            '-4dd1-ba58-d34d9480855a","name":"Ready to Start","color":"yellow"}'
            '},"Author":{"id":"qNw_","type":"multi_select","multi_select":[]},"'
            'Name":{"id":"title","type":"title","title":[{"type":"text","text":'
            '{"content":"New Media Article","link":null},"annotations":{"bold":'
            'false,"italic":false,"strikethrough":false,"underline":false,"code'
            '":false,"color":"default"},"plain_text":"New Media Article","href"'
            ':null}]}},"url":"https://www.notion.so/New-Media-Article-8f16061d4'
            'b774dbcbf04e8b0b4319b5a"},{"object":"page","id":"dc2a9117-163d-407'
            '5-907e-604b2f04c504","created_time":"2021-06-15T17:23:00.000Z","la'
            'st_edited_time":"2021-06-15T17:23:00.000Z","created_by":{"object":'
            '"user","id":"92a680bb-6970-4726-952b-4f4c03bff617"},"last_edited_b'
            'y":{"object":"user","id":"92a680bb-6970-4726-952b-4f4c03bff617"},"'
            'cover":null,"icon":null,"parent":{"type":"database_id","database_i'
            'd":"7a94f22f-59ae-484d-90ac-4aeddd667641"},"archived":false,"prope'
            'rties":{"Score /5":{"id":")Y7%22","type":"select","select":{"id":"'
            '5c944de7-3f4b-4567-b3a1-fa2c71c540b6","name":"⭐️⭐️⭐️⭐️⭐️","color":'
            '"default"}},"Type":{"id":"%2F7eo","type":"select","select":{"id":"'
            'f96d0d0a-5564-4a20-ab15-5f040d49759e","name":"Article","color":"de'
            'fault"}},"Publisher":{"id":"%3E%24Pb","type":"select","select":{"i'
            'd":"01f82d08-aa1f-4884-a4e0-3bc32f909ec4","name":"The Atlantic","c'
            'olor":"red"}},"Summary":{"id":"%3F%5C25","type":"rich_text","rich_'
            'text":[{"type":"text","text":{"content":"Some think chief ethics o'
            'fficers could help technology companies navigate political and soc'
            'ial questions.","link":null},"annotations":{"bold":false,"italic":'
            'false,"strikethrough":false,"underline":false,"code":false,"color"'
            ':"default"},"plain_text":"Some think chief ethics officers could h'
            'elp technology companies navigate political and social questions."'
            ',"href":null}]},"Publishing/Release Date":{"id":"%3Fex%2B","type":'
            '"date","date":{"start":"2020-12-08T12:00:00.000+00:00","end":null,'
            '"time_zone":null}},"date":{"id":"Lpwp","type":"date","date":null},'
            '"Link":{"id":"VVMi","type":"url","url":"https://www.nytimes.com/20'
            '18/10/21/opinion/who-will-teach-silicon-valley-to-be-ethical.html"'
            '},"Wine Pairing":{"id":"WO%40Z","type":"rich_text","rich_text":[]}'
            ',"Read":{"id":"_MWJ","type":"checkbox","checkbox":false},"Status":'
            '{"id":"%60zz5","type":"select","select":{"id":"8c4a056e-6709-4dd1-'
            'ba58-d34d9480855a","name":"Ready to Start","color":"yellow"}},"Aut'
            'hor":{"id":"qNw_","type":"multi_select","multi_select":[]},"Name":'
            '{"id":"title","type":"title","title":[{"type":"text","text":{"cont'
            'ent":"New Media Article","link":null},"annotations":{"bold":false,'
            '"italic":false,"strikethrough":false,"underline":false,"code":fals'
            'e,"color":"default"},"plain_text":"New Media Article","href":null}'
            ']}},"url":"https://www.notion.so/New-Media-Article-dc2a9117163d407'
            '5907e604b2f04c504"},{"object":"page","id":"c443c084-4637-4df2-ba37'
            '-b3c8a7e3d062","created_time":"2021-06-15T17:23:00.000Z","last_edi'
            'ted_time":"2021-06-15T17:23:00.000Z","created_by":{"object":"user"'
            ',"id":"92a680bb-6970-4726-952b-4f4c03bff617"},"last_edited_by":{"o'
            'bject":"user","id":"92a680bb-6970-4726-952b-4f4c03bff617"},"cover"'
            ':null,"icon":null,"parent":{"type":"database_id","database_id":"7a'
            '94f22f-59ae-484d-90ac-4aeddd667641"},"archived":false,"properties"'
            ':{"Score /5":{"id":")Y7%22","type":"select","select":{"id":"5c944d'
            'e7-3f4b-4567-b3a1-fa2c71c540b6","name":"⭐️⭐️⭐️⭐️⭐️","color":"defau'
            'lt"}},"Type":{"id":"%2F7eo","type":"select","select":{"id":"f96d0d'
            '0a-5564-4a20-ab15-5f040d49759e","name":"Article","color":"default"'
            '}},"Publisher":{"id":"%3E%24Pb","type":"select","select":{"id":"01'
            'f82d08-aa1f-4884-a4e0-3bc32f909ec4","name":"The Atlantic","color":'
            '"red"}},"Summary":{"id":"%3F%5C25","type":"rich_text","rich_text":'
            '[{"type":"text","text":{"content":"Some think chief ethics officer'
            's could help technology companies navigate political and social qu'
            'estions.","link":null},"annotations":{"bold":false,"italic":false,'
            '"strikethrough":false,"underline":false,"code":false,"color":"defa'
            'ult"},"plain_text":"Some think chief ethics officers could help te'
            'chnology companies navigate political and social questions.","href'
            '":null}]},"Publishing/Release Date":{"id":"%3Fex%2B","type":"date"'
            ',"date":{"start":"2020-12-08T12:00:00.000+00:00","end":null,"time_'
            'zone":null}},"date":{"id":"Lpwp","type":"date","date":null},"Link"'
            ':{"id":"VVMi","type":"url","url":"https://www.nytimes.com/2018/10/'
            '21/opinion/who-will-teach-silicon-valley-to-be-ethical.html"},"Win'
            'e Pairing":{"id":"WO%40Z","type":"rich_text","rich_text":[]},"Read'
            '":{"id":"_MWJ","type":"checkbox","checkbox":false},"Status":{"id":'
            '"%60zz5","type":"select","select":{"id":"8c4a056e-6709-4dd1-ba58-d'
            '34d9480855a","name":"Ready to Start","color":"yellow"}},"Author":{'
            '"id":"qNw_","type":"multi_select","multi_select":[]},"Name":{"id":'
            '"title","type":"title","title":[{"type":"text","text":{"content":"'
            'New Media Article","link":null},"annotations":{"bold":false,"itali'
            'c":false,"strikethrough":false,"underline":false,"code":false,"col'
            'or":"default"},"plain_text":"New Media Article","href":null}]}},"u'
            'rl":"https://www.notion.so/New-Media-Article-c443c08446374df2ba37b'
            '3c8a7e3d062"},{"object":"page","id":"0ac85319-05c5-4b5b-b812-7ea0f'
            '6476ea0","created_time":"2021-06-15T17:23:00.000Z","last_edited_ti'
            'me":"2021-06-15T17:23:00.000Z","created_by":{"object":"user","id":'
            '"92a680bb-6970-4726-952b-4f4c03bff617"},"last_edited_by":{"object"'
            ':"user","id":"92a680bb-6970-4726-952b-4f4c03bff617"},"cover":null,'
            '"icon":null,"parent":{"type":"database_id","database_id":"7a94f22f'
            '-59ae-484d-90ac-4aeddd667641"},"archived":false,"properties":{"Sco'
            're /5":{"id":")Y7%22","type":"select","select":{"id":"5c944de7-3f4'
            'b-4567-b3a1-fa2c71c540b6","name":"⭐️⭐️⭐️⭐️⭐️","color":"default"}},'
            '"Type":{"id":"%2F7eo","type":"select","select":{"id":"f96d0d0a-556'
            '4-4a20-ab15-5f040d49759e","name":"Article","color":"default"}},"Pu'
            'blisher":{"id":"%3E%24Pb","type":"select","select":{"id":"01f82d08'
            '-aa1f-4884-a4e0-3bc32f909ec4","name":"The Atlantic","color":"red"}'
            '},"Summary":{"id":"%3F%5C25","type":"rich_text","rich_text":[{"typ'
            'e":"text","text":{"content":"Some think chief ethics officers coul'
            'd help technology companies navigate political and social question'
            's.","link":null},"annotations":{"bold":false,"italic":false,"strik'
            'ethrough":false,"underline":false,"code":false,"color":"default"},'
            '"plain_text":"Some think chief ethics officers could help technolo'
            'gy companies navigate political and social questions.","href":null'
            '}]},"Publishing/Release Date":{"id":"%3Fex%2B","type":"date","date'
            '":{"start":"2020-12-08T12:00:00.000+00:00","end":null,"time_zone":'
            'null}},"date":{"id":"Lpwp","type":"date","date":null},"Link":{"id"'
            ':"VVMi","type":"url","url":"https://www.nytimes.com/2018/10/21/opi'
            'nion/who-will-teach-silicon-valley-to-be-ethical.html"},"Wine Pair'
            'ing":{"id":"WO%40Z","type":"rich_text","rich_text":[]},"Read":{"id'
            '":"_MWJ","type":"checkbox","checkbox":false},"Status":{"id":"%60zz'
            '5","type":"select","select":{"id":"8c4a056e-6709-4dd1-ba58-d34d948'
            '0855a","name":"Ready to Start","color":"yellow"}},"Author":{"id":"'
            'qNw_","type":"multi_select","multi_select":[]},"Name":{"id":"title'
            '","type":"title","title":[{"type":"text","text":{"content":"New Me'
            'dia Article","link":null},"annotations":{"bold":false,"italic":fal'
            'se,"strikethrough":false,"underline":false,"code":false,"color":"d'
            'efault"},"plain_text":"New Media Article","href":null}]}},"url":"h'
            'ttps://www.notion.so/New-Media-Article-0ac8531905c54b5bb8127ea0f64'
            '76ea0"},{"object":"page","id":"794fc25a-7f59-419d-a6e5-d9f0b516ecc'
            '7","created_time":"2021-06-15T17:24:00.000Z","last_edited_time":"2'
            '021-06-15T17:24:00.000Z","created_by":{"object":"user","id":"92a68'
            '0bb-6970-4726-952b-4f4c03bff617"},"last_edited_by":{"object":"user'
            '","id":"92a680bb-6970-4726-952b-4f4c03bff617"},"cover":null,"icon"'
            ':null,"parent":{"type":"database_id","database_id":"7a94f22f-59ae-'
            '484d-90ac-4aeddd667641"},"archived":false,"properties":{"Score /5"'
            ':{"id":")Y7%22","type":"select","select":{"id":"5c944de7-3f4b-4567'
            '-b3a1-fa2c71c540b6","name":"⭐️⭐️⭐️⭐️⭐️","color":"default"}},"Type"'
            ':{"id":"%2F7eo","type":"select","select":{"id":"f96d0d0a-5564-4a20'
            '-ab15-5f040d49759e","name":"Article","color":"default"}},"Publishe'
            'r":{"id":"%3E%24Pb","type":"select","select":{"id":"01f82d08-aa1f-'
            '4884-a4e0-3bc32f909ec4","name":"The Atlantic","color":"red"}},"Sum'
            'mary":{"id":"%3F%5C25","type":"rich_text","rich_text":[{"type":"te'
            'xt","text":{"content":"Some think chief ethics officers could help'
            ' technology companies navigate political and social questions.","l'
            'ink":null},"annotations":{"bold":false,"italic":false,"strikethrou'
            'gh":false,"underline":false,"code":false,"color":"default"},"plain'
            '_text":"Some think chief ethics officers could help technology com'
            'panies navigate political and social questions.","href":null}]},"P'
            'ublishing/Release Date":{"id":"%3Fex%2B","type":"date","date":{"st'
            'art":"2020-12-08T12:00:00.000+00:00","end":null,"time_zone":null}}'
            ',"date":{"id":"Lpwp","type":"date","date":null},"Link":{"id":"VVMi'
            '","type":"url","url":"https://www.nytimes.com/2018/10/21/opinion/w'
            'ho-will-teach-silicon-valley-to-be-ethical.html"},"Wine Pairing":{'
            '"id":"WO%40Z","type":"rich_text","rich_text":[]},"Read":{"id":"_MW'
            'J","type":"checkbox","checkbox":false},"Status":{"id":"%60zz5","ty'
            'pe":"select","select":{"id":"8c4a056e-6709-4dd1-ba58-d34d9480855a"'
            ',"name":"Ready to Start","color":"yellow"}},"Author":{"id":"qNw_",'
            '"type":"multi_select","multi_select":[]},"Name":{"id":"title","typ'
            'e":"title","title":[{"type":"text","text":{"content":"New Media Ar'
            'ticle","link":null},"annotations":{"bold":false,"italic":false,"st'
            'rikethrough":false,"underline":false,"code":false,"color":"default'
            '"},"plain_text":"New Media Article","href":null}]}},"url":"https:/'
            '/www.notion.so/New-Media-Article-794fc25a7f59419da6e5d9f0b516ecc7"'
            '},{"object":"page","id":"41ad30b7-98e7-4c55-bf21-7ac7f09c2fd5","cr'
            'eated_time":"2021-06-15T17:24:00.000Z","last_edited_time":"2021-06'
            '-15T17:24:00.000Z","created_by":{"object":"user","id":"92a680bb-69'
            '70-4726-952b-4f4c03bff617"},"last_edited_by":{"object":"user","id"'
            ':"92a680bb-6970-4726-952b-4f4c03bff617"},"cover":null,"icon":null,'
            '"parent":{"type":"database_id","database_id":"7a94f22f-59ae-484d-9'
            '0ac-4aeddd667641"},"archived":false,"properties":{"Score /5":{"id"'
            ':")Y7%22","type":"select","select":{"id":"5c944de7-3f4b-4567-b3a1-'
            'fa2c71c540b6","name":"⭐️⭐️⭐️⭐️⭐️","color":"default"}},"Type":{"id"'
            ':"%2F7eo","type":"select","select":{"id":"f96d0d0a-5564-4a20-ab15-'
            '5f040d49759e","name":"Article","color":"default"}},"Publisher":{"i'
            'd":"%3E%24Pb","type":"select","select":{"id":"01f82d08-aa1f-4884-a'
            '4e0-3bc32f909ec4","name":"The Atlantic","color":"red"}},"Summary":'
            '{"id":"%3F%5C25","type":"rich_text","rich_text":[{"type":"text","t'
            'ext":{"content":"Some think chief ethics officers could help techn'
            'ology companies navigate political and social questions.","link":n'
            'ull},"annotations":{"bold":false,"italic":false,"strikethrough":fa'
            'lse,"underline":false,"code":false,"color":"default"},"plain_text"'
            ':"Some think chief ethics officers could help technology companies'
            ' navigate political and social questions.","href":null}]},"Publish'
            'ing/Release Date":{"id":"%3Fex%2B","type":"date","date":{"start":"'
            '2020-12-08T12:00:00.000+00:00","end":null,"time_zone":null}},"date'
            '":{"id":"Lpwp","type":"date","date":null},"Link":{"id":"VVMi","typ'
            'e":"url","url":"https://www.nytimes.com/2018/10/21/opinion/who-wil'
            'l-teach-silicon-valley-to-be-ethical.html"},"Wine Pairing":{"id":"'
            'WO%40Z","type":"rich_text","rich_text":[]},"Read":{"id":"_MWJ","ty'
            'pe":"checkbox","checkbox":false},"Status":{"id":"%60zz5","type":"s'
            'elect","select":{"id":"b598e780-263b-4b02-862c-9bf7a91859ac","name'
            '":"New Option","color":"orange"}},"Author":{"id":"qNw_","type":"mu'
            'lti_select","multi_select":[]},"Name":{"id":"title","type":"title"'
            ',"title":[{"type":"text","text":{"content":"New Media Article","li'
            'nk":null},"annotations":{"bold":false,"italic":false,"strikethroug'
            'h":false,"underline":false,"code":false,"color":"default"},"plain_'
            'text":"New Media Article","href":null}]}},"url":"https://www.notio'
            'n.so/New-Media-Article-41ad30b798e74c55bf217ac7f09c2fd5"},{"object'
            '":"page","id":"6a313bae-fdd3-4617-9bd6-5b132f23be35","created_time'
            '":"2021-06-15T17:24:00.000Z","last_edited_time":"2021-06-15T17:24:'
            '00.000Z","created_by":{"object":"user","id":"92a680bb-6970-4726-95'
            '2b-4f4c03bff617"},"last_edited_by":{"object":"user","id":"92a680bb'
            '-6970-4726-952b-4f4c03bff617"},"cover":null,"icon":null,"parent":{'
            '"type":"database_id","database_id":"7a94f22f-59ae-484d-90ac-4aeddd'
            '667641"},"archived":false,"properties":{"Score /5":{"id":")Y7%22",'
            '"type":"select","select":{"id":"5c944de7-3f4b-4567-b3a1-fa2c71c540'
            'b6","name":"⭐️⭐️⭐️⭐️⭐️","color":"default"}},"Type":{"id":"%2F7eo",'
            '"type":"select","select":{"id":"f96d0d0a-5564-4a20-ab15-5f040d4975'
            '9e","name":"Article","color":"default"}},"Publisher":{"id":"%3E%24'
            'Pb","type":"select","select":{"id":"01f82d08-aa1f-4884-a4e0-3bc32f'
            '909ec4","name":"The Atlantic","color":"red"}},"Summary":{"id":"%3F'
            '%5C25","type":"rich_text","rich_text":[{"type":"text","text":{"con'
            'tent":"Some think chief ethics officers could help technology comp'
            'anies navigate political and social questions.","link":null},"anno'
            'tations":{"bold":false,"italic":false,"strikethrough":false,"under'
            'line":false,"code":false,"color":"default"},"plain_text":"Some thi'
            'nk chief ethics officers could help technology companies navigate '
            'political and social questions.","href":null}]},"Publishing/Releas'
            'e Date":{"id":"%3Fex%2B","type":"date","date":{"start":"2020-12-08'
            'T12:00:00.000+00:00","end":null,"time_zone":null}},"date":{"id":"L'
            'pwp","type":"date","date":null},"Link":{"id":"VVMi","type":"url","'
            'url":"https://www.nytimes.com/2018/10/21/opinion/who-will-teach-si'
            'licon-valley-to-be-ethical.html"},"Wine Pairing":{"id":"WO%40Z","t'
            'ype":"rich_text","rich_text":[]},"Read":{"id":"_MWJ","type":"check'
            'box","checkbox":false},"Status":{"id":"%60zz5","type":"select","se'
            'lect":{"id":"ad038109-97d3-4b5d-a93a-3b88229b1b58","name":"New Opt'
            'ion 3","color":"purple"}},"Author":{"id":"qNw_","type":"multi_sele'
            'ct","multi_select":[]},"Name":{"id":"title","type":"title","title"'
            ':[{"type":"text","text":{"content":"New Media Article","link":null'
            '},"annotations":{"bold":false,"italic":false,"strikethrough":false'
            ',"underline":false,"code":false,"color":"default"},"plain_text":"N'
            'ew Media Article","href":null}]}},"url":"https://www.notion.so/New'
            '-Media-Article-6a313baefdd346179bd65b132f23be35"}],"next_cursor":n'
            'ull,"has_more":false}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

