# -*- coding: utf-8 -*-

"""
notionapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from notionapi.api_helper import APIHelper


class BlocksControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(BlocksControllerTests, cls).setUpClass()
        cls.controller = cls.client.blocks
        cls.response_catcher = cls.controller.http_call_back

    # Retrieve block children
    def test_retrieve_block_children(self):
        # Parameters for the API call
        id = '{{PAGE_ID}}'
        notion_version = '{{NOTION_VERSION}}'
        page_size = 100

        # Perform the API call through the SDK function
        result = self.controller.retrieve_block_children(id, notion_version, page_size)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['date'] = None
        expected_headers['transfer-encoding'] = None
        expected_headers['connection'] = None
        expected_headers['x-dns-prefetch-control'] = None
        expected_headers['x-frame-options'] = None
        expected_headers['strict-transport-security'] = None
        expected_headers['x-download-options'] = None
        expected_headers['x-content-type-options'] = None
        expected_headers['x-xss-protection'] = None
        expected_headers['referrer-policy'] = None
        expected_headers['content-security-policy'] = None
        expected_headers['x-content-security-policy'] = None
        expected_headers['x-webkit-csp'] = None
        expected_headers['set-cookie'] = None
        expected_headers['etag'] = None
        expected_headers['vary'] = None
        expected_headers['content-encoding'] = None
        expected_headers['cf-cache-status'] = None
        expected_headers['cf-request-id'] = None
        expected_headers['expect-ct'] = None
        expected_headers['server'] = None
        expected_headers['cf-ray'] = None
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"object":"list","results":[{"object":"block","id":"48c1ffb5-2789-'
            '4025-937b-2c35eaaaab3f","created_time":"2021-04-27T20:38:19.437Z",'
            '"last_edited_time":"2021-04-27T20:38:19.437Z","has_children":false'
            ',"type":"unsupported","unsupported":{}},{"object":"block","id":"e3'
            '81a0a3-4efb-4ba9-aa93-45b70fa9ce7f","created_time":"2021-04-27T20:'
            '38:19.437Z","last_edited_time":"2021-04-27T20:38:19.437Z","has_chi'
            'ldren":false,"type":"paragraph","paragraph":{"text":[{"type":"text'
            '","text":{"content":"I think we can all agree that Silicon Valley '
            'needs more adult supervision right about now.","link":null},"annot'
            'ations":{"bold":false,"italic":false,"strikethrough":false,"underl'
            'ine":false,"code":false,"color":"default"},"plain_text":"I think w'
            'e can all agree that Silicon Valley needs more adult supervision r'
            'ight about now.","href":null}]}},{"object":"block","id":"ce5f79ac-'
            '8145-44ab-be3b-8ad143d6f8a7","created_time":"2021-04-27T20:38:19.4'
            '37Z","last_edited_time":"2021-04-27T20:38:19.437Z","has_children":'
            'false,"type":"paragraph","paragraph":{"text":[{"type":"text","text'
            '":{"content":"Is the solution for its companies to hire a chief et'
            'hics officer?","link":null},"annotations":{"bold":false,"italic":f'
            'alse,"strikethrough":false,"underline":false,"code":false,"color":'
            '"default"},"plain_text":"Is the solution for its companies to hire'
            ' a chief ethics officer?","href":null}]}},{"object":"block","id":"'
            '0387b374-7847-4ddc-bc53-6b0813ce4ed4","created_time":"2021-04-27T2'
            '0:38:19.437Z","last_edited_time":"2021-04-27T20:38:19.437Z","has_c'
            'hildren":false,"type":"paragraph","paragraph":{"text":[{"type":"te'
            'xt","text":{"content":"While some tech companies like Google have '
            'top compliance officers and others turn to legal teams to police t'
            'hemselves, no big tech companies that I know of have yet taken thi'
            's step. But a lot of them seem to be talking about it, and I’ve di'
            'scussed the idea with several chief executives recently. Why? Beca'
            'use slowly, then all at once, it feels like too many digital leade'
            'rs have lost their minds.","link":null},"annotations":{"bold":fals'
            'e,"italic":false,"strikethrough":false,"underline":false,"code":fa'
            'lse,"color":"default"},"plain_text":"While some tech companies lik'
            'e Google have top compliance officers and others turn to legal tea'
            'ms to police themselves, no big tech companies that I know of have'
            ' yet taken this step. But a lot of them seem to be talking about i'
            't, and I’ve discussed the idea with several chief executives recen'
            'tly. Why? Because slowly, then all at once, it feels like too many'
            ' digital leaders have lost their minds.","href":null}]}},{"object"'
            ':"block","id":"da035311-5af3-48bc-8279-d28d9f4ef2e2","created_time'
            '":"2021-04-27T20:38:19.437Z","last_edited_time":"2021-04-27T20:38:'
            '19.437Z","has_children":false,"type":"paragraph","paragraph":{"tex'
            't":[{"type":"text","text":{"content":"It’s probably no surprise, c'
            'onsidering the complex problems the tech industry faces. As one et'
            'hical quandary after another has hit its profoundly ill-prepared e'
            'xecutives, their once-pristine reputations have fallen like palm t'
            'rees in a hurricane. These last two weeks alone show how tech is s'
            'tumbling to react to big world issues armed with only bubble world'
            ' skills:","link":null},"annotations":{"bold":false,"italic":false,'
            '"strikethrough":false,"underline":false,"code":false,"color":"defa'
            'ult"},"plain_text":"It’s probably no surprise, considering the com'
            'plex problems the tech industry faces. As one ethical quandary aft'
            'er another has hit its profoundly ill-prepared executives, their o'
            'nce-pristine reputations have fallen like palm trees in a hurrican'
            'e. These last two weeks alone show how tech is stumbling to react '
            'to big world issues armed with only bubble world skills:","href":n'
            'ull}]}},{"object":"block","id":"63a60fca-4a11-43eb-8773-c5f0164a31'
            '17","created_time":"2021-04-27T20:38:19.437Z","last_edited_time":"'
            '2021-04-27T20:38:19.437Z","has_children":false,"type":"paragraph",'
            '"paragraph":{"text":[{"type":"text","text":{"content":"As a journa'
            'list is beheaded and dismembered at the direction of Saudi Arabian'
            ' leaders (allegedly, but the killers did bring a bone saw), Silico'
            'n Valley is swimming in oceans of money from the kingdom’s Public '
            'Investment Fund. Saudi funding includes hundreds of millions for M'
            'agic Leap, and huge investments in hot public companies like Tesla'
            '. Most significantly: Saudis have invested about $45 billion in So'
            'ftBank’s giant Vision Fund, which has in turn doused the tech land'
            'scape — $4.4 billion to WeWork, $250 million to Slack, and $300 mi'
            'llion to the dog-walking app Wag. In total Uber has gotten almost '
            '$14 billion, either through direct investments from the Public Inv'
            'estment Fund or through the Saudis’ funding of the Vision Fund. A '
            'billion here, a billion there and it all adds up.","link":null},"a'
            'nnotations":{"bold":false,"italic":false,"strikethrough":false,"un'
            'derline":false,"code":false,"color":"default"},"plain_text":"As a '
            'journalist is beheaded and dismembered at the direction of Saudi A'
            'rabian leaders (allegedly, but the killers did bring a bone saw), '
            'Silicon Valley is swimming in oceans of money from the kingdom’s P'
            'ublic Investment Fund. Saudi funding includes hundreds of millions'
            ' for Magic Leap, and huge investments in hot public companies like'
            ' Tesla. Most significantly: Saudis have invested about $45 billion'
            ' in SoftBank’s giant Vision Fund, which has in turn doused the tec'
            'h landscape — $4.4 billion to WeWork, $250 million to Slack, and $'
            '300 million to the dog-walking app Wag. In total Uber has gotten a'
            'lmost $14 billion, either through direct investments from the Publ'
            'ic Investment Fund or through the Saudis’ funding of the Vision Fu'
            'nd. A billion here, a billion there and it all adds up.","href":nu'
            'll}]}},{"object":"block","id":"8c58c8f1-86ae-4a14-b6b9-74f5fa57962'
            '0","created_time":"2021-04-27T20:38:19.437Z","last_edited_time":"2'
            '021-04-27T20:38:19.437Z","has_children":false,"type":"paragraph","'
            'paragraph":{"text":[{"type":"text","text":{"content":"[","link":nu'
            'll},"annotations":{"bold":false,"italic":false,"strikethrough":fal'
            'se,"underline":false,"code":false,"color":"default"},"plain_text":'
            '"[","href":null},{"type":"text","text":{"content":"Kara Swisher an'
            'swered your questions about her column ","link":null},"annotations'
            '":{"bold":false,"italic":true,"strikethrough":false,"underline":fa'
            'lse,"code":false,"color":"default"},"plain_text":"Kara Swisher ans'
            'wered your questions about her column ","href":null},{"type":"text'
            '","text":{"content":"on Twitter","link":{"url":"https://twitter.co'
            'm/karaswisher/status/1054842303922298880"}},"annotations":{"bold":'
            'false,"italic":true,"strikethrough":false,"underline":false,"code"'
            ':false,"color":"default"},"plain_text":"on Twitter","href":"https:'
            '//twitter.com/karaswisher/status/1054842303922298880"},{"type":"te'
            'xt","text":{"content":".","link":null},"annotations":{"bold":false'
            ',"italic":true,"strikethrough":false,"underline":false,"code":fals'
            'e,"color":"default"},"plain_text":".","href":null},{"type":"text",'
            '"text":{"content":"]","link":null},"annotations":{"bold":false,"it'
            'alic":false,"strikethrough":false,"underline":false,"code":false,"'
            'color":"default"},"plain_text":"]","href":null}]}},{"object":"bloc'
            'k","id":"875d3aff-086b-45da-9ed1-bc3ddb185229","created_time":"202'
            '1-04-27T20:38:19.437Z","last_edited_time":"2021-04-27T20:38:19.437'
            'Z","has_children":false,"type":"paragraph","paragraph":{"text":[{"'
            'type":"text","text":{"content":"Facebook introduced a new home vid'
            'eo device called Portal, and promised that what could be seen as a'
            ' surveillance tool would not share data for the sake of ad targeti'
            'ng. Soon after, as ","link":null},"annotations":{"bold":false,"ita'
            'lic":false,"strikethrough":false,"underline":false,"code":false,"c'
            'olor":"default"},"plain_text":"Facebook introduced a new home vide'
            'o device called Portal, and promised that what could be seen as a '
            'surveillance tool would not share data for the sake of ad targetin'
            'g. Soon after, as ","href":null},{"type":"text","text":{"content":'
            '"reported by Recode","link":{"url":"https://www.recode.net/2018/10'
            '/16/17966102/facebook-portal-ad-targeting-data-collection"}},"anno'
            'tations":{"bold":false,"italic":false,"strikethrough":false,"under'
            'line":false,"code":false,"color":"default"},"plain_text":"reported'
            ' by Recode","href":"https://www.recode.net/2018/10/16/17966102/fac'
            'ebook-portal-ad-targeting-data-collection"},{"type":"text","text":'
            '{"content":", Facebook admitted that “data about who you call and '
            'data about which apps you use on Portal ","link":null},"annotation'
            's":{"bold":false,"italic":false,"strikethrough":false,"underline":'
            'false,"code":false,"color":"default"},"plain_text":", Facebook adm'
            'itted that “data about who you call and data about which apps you '
            'use on Portal ","href":null},{"type":"text","text":{"content":"can'
            '","link":null},"annotations":{"bold":false,"italic":true,"striketh'
            'rough":false,"underline":false,"code":false,"color":"default"},"pl'
            'ain_text":"can","href":null},{"type":"text","text":{"content":" be'
            ' used to target you with ads on other Facebook-owned properties.” '
            'Oh. Um. That’s awkward.","link":null},"annotations":{"bold":false,'
            '"italic":false,"strikethrough":false,"underline":false,"code":fals'
            'e,"color":"default"},"plain_text":" be used to target you with ads'
            ' on other Facebook-owned properties.” Oh. Um. That’s awkward.","hr'
            'ef":null}]}},{"object":"block","id":"306ab0fb-6daa-4c5b-b1f7-f51a5'
            'f92b6ff","created_time":"2021-04-27T20:38:19.437Z","last_edited_ti'
            'me":"2021-04-27T20:38:19.437Z","has_children":false,"type":"paragr'
            'aph","paragraph":{"text":[{"type":"text","text":{"content":"After '
            'agreeing to pay $20 million to the Securities and Exchange Commiss'
            'ion for an ill-advised tweet about possible funding (from the Saud'
            'is, by the way), the Tesla co-founder Elon Musk proceeded to troll'
            ' the regulatory agency on, you got it, Twitter. And even though th'
            'e ","link":null},"annotations":{"bold":false,"italic":false,"strik'
            'ethrough":false,"underline":false,"code":false,"color":"default"},'
            '"plain_text":"After agreeing to pay $20 million to the Securities '
            'and Exchange Commission for an ill-advised tweet about possible fu'
            'nding (from the Saudis, by the way), the Tesla co-founder Elon Mus'
            'k proceeded to troll the regulatory agency on, you got it, Twitter'
            '. And even though the ","href":null},{"type":"text","text":{"conte'
            'nt":"settlement called for some kind of control of his communicati'
            'ons","link":{"url":"https://www.sec.gov/news/press-release/2018-22'
            '6"}},"annotations":{"bold":false,"italic":false,"strikethrough":fa'
            'lse,"underline":false,"code":false,"color":"default"},"plain_text"'
            ':"settlement called for some kind of control of his communications'
            '","href":"https://www.sec.gov/news/press-release/2018-226"},{"type'
            '":"text","text":{"content":", it appears that Mr. Musk will contin'
            'ue tweeting until someone steals his phone.","link":null},"annotat'
            'ions":{"bold":false,"italic":false,"strikethrough":false,"underlin'
            'e":false,"code":false,"color":"default"},"plain_text":", it appear'
            's that Mr. Musk will continue tweeting until someone steals his ph'
            'one.","href":null}]}},{"object":"block","id":"122b1457-4129-4513-a'
            'baa-7cce7d66e4a1","created_time":"2021-04-27T20:38:19.437Z","last_'
            'edited_time":"2021-04-27T20:38:19.437Z","has_children":false,"type'
            '":"paragraph","paragraph":{"text":[{"type":"text","text":{"content'
            '":"Finally, Google took six months to make public that user data o'
            'n its social network, Google Plus, ","link":null},"annotations":{"'
            'bold":false,"italic":false,"strikethrough":false,"underline":false'
            ',"code":false,"color":"default"},"plain_text":"Finally, Google too'
            'k six months to make public that user data on its social network, '
            'Google Plus, ","href":null},{"type":"text","text":{"content":"had '
            'been exposed","link":{"url":"https://www.nytimes.com/2018/10/08/te'
            'chnology/google-plus-security-disclosure.html?module=inline"}},"an'
            'notations":{"bold":false,"italic":false,"strikethrough":false,"und'
            'erline":false,"code":false,"color":"default"},"plain_text":"had be'
            'en exposed","href":"https://www.nytimes.com/2018/10/08/technology/'
            'google-plus-security-disclosure.html?module=inline"},{"type":"text'
            '","text":{"content":" and that profiles of up to 500,000 users may'
            ' have been compromised. While the service failed long ago, because'
            ' it was pretty much designed by antisocial people, this lack of co'
            'ncern for privacy was profound.","link":null},"annotations":{"bold'
            '":false,"italic":false,"strikethrough":false,"underline":false,"co'
            'de":false,"color":"default"},"plain_text":" and that profiles of u'
            'p to 500,000 users may have been compromised. While the service fa'
            'iled long ago, because it was pretty much designed by antisocial p'
            'eople, this lack of concern for privacy was profound.","href":null'
            '}]}},{"object":"block","id":"4d4af599-556f-4d8b-af8e-4d01ebe2aa27"'
            ',"created_time":"2021-04-27T20:38:19.437Z","last_edited_time":"202'
            '1-04-27T20:38:19.437Z","has_children":false,"type":"paragraph","pa'
            'ragraph":{"text":[{"type":"text","text":{"content":"Grappling with'
            ' what to say and do about the disasters they themselves create is '
            'only the beginning. Then there are the broader issues that the den'
            'izens of Silicon Valley expect their employers to have a stance on'
            ': immigration, income inequality, artificial intelligence, automat'
            'ion, transgender rights, climate change, privacy, data rights and '
            'whether tech companies should be helping the government do controv'
            'ersial things. It’s an ethical swamp out there.","link":null},"ann'
            'otations":{"bold":false,"italic":false,"strikethrough":false,"unde'
            'rline":false,"code":false,"color":"default"},"plain_text":"Grappli'
            'ng with what to say and do about the disasters they themselves cre'
            'ate is only the beginning. Then there are the broader issues that '
            'the denizens of Silicon Valley expect their employers to have a st'
            'ance on: immigration, income inequality, artificial intelligence, '
            'automation, transgender rights, climate change, privacy, data righ'
            'ts and whether tech companies should be helping the government do '
            'controversial things. It’s an ethical swamp out there.","href":nul'
            'l}]}},{"object":"block","id":"f5775df5-59eb-4533-a2cb-e150412ec4f6'
            '","created_time":"2021-04-27T20:38:19.437Z","last_edited_time":"20'
            '21-04-27T20:38:19.437Z","has_children":false,"type":"paragraph","p'
            'aragraph":{"text":[{"type":"text","text":{"content":"That’s why, i'
            'n a recent interview, Marc Benioff, the co-chief executive and a f'
            'ounder of Salesforce, told me he was in the process of hiring a ch'
            'ief ethical officer to help anticipate and address any thorny conu'
            'ndrums it might encounter as a business — like the decision it had'
            ' to make a few months back about whether it should stop providing '
            'recruitment software for Customs and Border Protection because of '
            'the government’s policy of separating immigrant families at the bo'
            'rder.","link":null},"annotations":{"bold":false,"italic":false,"st'
            'rikethrough":false,"underline":false,"code":false,"color":"default'
            '"},"plain_text":"That’s why, in a recent interview, Marc Benioff, '
            'the co-chief executive and a founder of Salesforce, told me he was'
            ' in the process of hiring a chief ethical officer to help anticipa'
            'te and address any thorny conundrums it might encounter as a busin'
            'ess — like the decision it had to make a few months back about whe'
            'ther it should stop providing recruitment software for Customs and'
            ' Border Protection because of the government’s policy of separatin'
            'g immigrant families at the border.","href":null}]}},{"object":"bl'
            'ock","id":"31405c6e-7ece-4667-8c4d-36c9d79a0bfa","created_time":"2'
            '021-04-27T20:38:19.437Z","last_edited_time":"2021-04-27T20:38:19.4'
            '37Z","has_children":false,"type":"paragraph","paragraph":{"text":['
            '{"type":"text","text":{"content":"Amid much criticism, Mr. Benioff'
            ' decided to keep the contract, but said he would focus more on soc'
            'ial and political issues.","link":null},"annotations":{"bold":fals'
            'e,"italic":false,"strikethrough":false,"underline":false,"code":fa'
            'lse,"color":"default"},"plain_text":"Amid much criticism, Mr. Beni'
            'off decided to keep the contract, but said he would focus more on '
            'social and political issues.","href":null}]}},{"object":"block","i'
            'd":"a2ab7e8a-d521-401d-89ae-9eb27efb9990","created_time":"2021-04-'
            '27T20:38:19.437Z","last_edited_time":"2021-04-27T20:38:19.437Z","h'
            'as_children":false,"type":"paragraph","paragraph":{"text":[{"type"'
            ':"text","text":{"content":"At a recent company event, he elaborate'
            'd: “We can have a structured conversation not just with our own em'
            'ployees myopically, but by bringing in the key advisers, supporter'
            's and pundits and philosophers and everybody necessary to ask the '
            'question if what we are doing today is ethical and humane.”","link'
            '":null},"annotations":{"bold":false,"italic":false,"strikethrough"'
            ':false,"underline":false,"code":false,"color":"default"},"plain_te'
            'xt":"At a recent company event, he elaborated: “We can have a stru'
            'ctured conversation not just with our own employees myopically, bu'
            't by bringing in the key advisers, supporters and pundits and phil'
            'osophers and everybody necessary to ask the question if what we ar'
            'e doing today is ethical and humane.”","href":null}]}},{"object":"'
            'block","id":"a4498e1e-8b85-48d7-802a-db447ca7d1ac","created_time":'
            '"2021-04-27T20:38:19.437Z","last_edited_time":"2021-04-27T20:38:19'
            '.437Z","has_children":false,"type":"paragraph","paragraph":{"text"'
            ':[{"type":"text","text":{"content":"23andMe has also toyed with th'
            'e idea of hiring a chief ethics officer. In an interview I did thi'
            's week with its chief executive, Anne Wojcicki, she said the genet'
            'ics company had even interviewed candidates, but that many of them'
            ' wanted to remain in academia to be freer to ponder these issues. '
            'She acknowledged that the collection of DNA data is rife with ethi'
            'cal considerations, but said, “I think it has to be our management'
            ' and leaders who have to add this to our skill set, rather than ju'
            'st hire one person to determine this.”","link":null},"annotations"'
            ':{"bold":false,"italic":false,"strikethrough":false,"underline":fa'
            'lse,"code":false,"color":"default"},"plain_text":"23andMe has also'
            ' toyed with the idea of hiring a chief ethics officer. In an inter'
            'view I did this week with its chief executive, Anne Wojcicki, she '
            'said the genetics company had even interviewed candidates, but tha'
            't many of them wanted to remain in academia to be freer to ponder '
            'these issues. She acknowledged that the collection of DNA data is '
            'rife with ethical considerations, but said, “I think it has to be '
            'our management and leaders who have to add this to our skill set, '
            'rather than just hire one person to determine this.”","href":null}'
            ']}},{"object":"block","id":"cbf7e7e0-5552-4b3f-b09e-9dcca120931c",'
            '"created_time":"2021-04-27T20:38:19.437Z","last_edited_time":"2021'
            '-04-27T20:38:19.437Z","has_children":false,"type":"paragraph","par'
            'agraph":{"text":[{"type":"text","text":{"content":"When asked abou'
            't the idea of a single source of wisdom on ethics, some point out '
            'that legal or diversity/inclusion departments are designed for tha'
            't purpose and that the ethics should really come from the top — th'
            'e chief executive.","link":null},"annotations":{"bold":false,"ital'
            'ic":false,"strikethrough":false,"underline":false,"code":false,"co'
            'lor":"default"},"plain_text":"When asked about the idea of a singl'
            'e source of wisdom on ethics, some point out that legal or diversi'
            'ty/inclusion departments are designed for that purpose and that th'
            'e ethics should really come from the top — the chief executive.","'
            'href":null}]}},{"object":"block","id":"d24b2887-0f1f-4e91-99c1-c29'
            '5bed8ad65","created_time":"2021-04-27T20:38:19.437Z","last_edited_'
            'time":"2021-04-27T20:38:19.437Z","has_children":false,"type":"para'
            'graph","paragraph":{"text":[{"type":"text","text":{"content":"Also'
            ' of concern is the possibility that a single person would not get '
            'listened to or, worse, get steamrollered. And, if the person was b'
            'ad at the job, of course, it could drag the whole thing down.","li'
            'nk":null},"annotations":{"bold":false,"italic":false,"strikethroug'
            'h":false,"underline":false,"code":false,"color":"default"},"plain_'
            'text":"Also of concern is the possibility that a single person wou'
            'ld not get listened to or, worse, get steamrollered. And, if the p'
            'erson was bad at the job, of course, it could drag the whole thing'
            ' down.","href":null}]}},{"object":"block","id":"78c55f65-c8b8-4364'
            '-a369-c40699968e90","created_time":"2021-04-27T20:38:19.437Z","las'
            't_edited_time":"2021-04-27T20:38:19.437Z","has_children":false,"ty'
            'pe":"paragraph","paragraph":{"text":[{"type":"text","text":{"conte'
            'nt":"Others are more worried that the move would be nothing but wi'
            'ndow dressing. One consultant who focuses on ethics, but did not w'
            'ant to be named, told me: “We haven’t even defined ethics, so what'
            ' even is ethical use, especially for Silicon Valley companies that'
            ' are babies in this game?”","link":null},"annotations":{"bold":fal'
            'se,"italic":false,"strikethrough":false,"underline":false,"code":f'
            'alse,"color":"default"},"plain_text":"Others are more worried that'
            ' the move would be nothing but window dressing. One consultant who'
            ' focuses on ethics, but did not want to be named, told me: “We hav'
            'en’t even defined ethics, so what even is ethical use, especially '
            'for Silicon Valley companies that are babies in this game?”","href'
            '":null}]}},{"object":"block","id":"0b492111-1586-4a73-8848-04f0c39'
            '1aadc","created_time":"2021-04-27T20:38:19.437Z","last_edited_time'
            '":"2021-04-27T20:38:19.437Z","has_children":false,"type":"paragrap'
            'h","paragraph":{"text":[{"type":"text","text":{"content":"How can '
            'an industry that, unlike other business sectors, persistently prom'
            'otes itself as doing good, learn to do that in reality? Do you wan'
            't to not do harm, or do you want to do good? These are two totally'
            ' different things.","link":null},"annotations":{"bold":false,"ital'
            'ic":false,"strikethrough":false,"underline":false,"code":false,"co'
            'lor":"default"},"plain_text":"How can an industry that, unlike oth'
            'er business sectors, persistently promotes itself as doing good, l'
            'earn to do that in reality? Do you want to not do harm, or do you '
            'want to do good? These are two totally different things.","href":n'
            'ull}]}},{"object":"block","id":"302f8229-2404-460b-8c3c-e7058b4365'
            'e5","created_time":"2021-04-27T20:38:19.437Z","last_edited_time":"'
            '2021-04-27T20:38:19.437Z","has_children":false,"type":"paragraph",'
            '"paragraph":{"text":[{"type":"text","text":{"content":"And how do '
            'you put an official ethical system in place without it seeming lik'
            'e you’re telling everyone how to behave? Who gets to decide those '
            'rules anyway, setting a moral path for the industry and — consider'
            'ing tech companies’ enormous power — the world.","link":null},"ann'
            'otations":{"bold":false,"italic":false,"strikethrough":false,"unde'
            'rline":false,"code":false,"color":"default"},"plain_text":"And how'
            ' do you put an official ethical system in place without it seeming'
            ' like you’re telling everyone how to behave? Who gets to decide th'
            'ose rules anyway, setting a moral path for the industry and — cons'
            'idering tech companies’ enormous power — the world.","href":null}]'
            '}},{"object":"block","id":"8f9bc91c-5662-4b3f-a110-809f46b79f49","'
            'created_time":"2021-04-27T20:38:19.437Z","last_edited_time":"2021-'
            '04-27T20:38:19.437Z","has_children":false,"type":"paragraph","para'
            'graph":{"text":[{"type":"text","text":{"content":"Like I said, adu'
            'lt supervision. Or maybe, better still, Silicon Valley itself has '
            'to grow up.","link":null},"annotations":{"bold":false,"italic":fal'
            'se,"strikethrough":false,"underline":false,"code":false,"color":"d'
            'efault"},"plain_text":"Like I said, adult supervision. Or maybe, b'
            'etter still, Silicon Valley itself has to grow up.","href":null}]}'
            '},{"object":"block","id":"7bea1831-a25c-4b3e-8c9b-b37de814f948","c'
            'reated_time":"2021-04-27T20:38:19.437Z","last_edited_time":"2021-0'
            '4-27T20:38:19.437Z","has_children":false,"type":"paragraph","parag'
            'raph":{"text":[{"type":"text","text":{"content":"Follow The New Yo'
            'rk Times Opinion section on ","link":null},"annotations":{"bold":f'
            'alse,"italic":true,"strikethrough":false,"underline":false,"code":'
            'false,"color":"default"},"plain_text":"Follow The New York Times O'
            'pinion section on ","href":null},{"type":"text","text":{"content":'
            '"Facebook","link":{"url":"https://www.facebook.com/nytopinion"}},"'
            'annotations":{"bold":false,"italic":true,"strikethrough":false,"un'
            'derline":false,"code":false,"color":"default"},"plain_text":"Faceb'
            'ook","href":"https://www.facebook.com/nytopinion"},{"type":"text",'
            '"text":{"content":", ","link":null},"annotations":{"bold":false,"i'
            'talic":true,"strikethrough":false,"underline":false,"code":false,"'
            'color":"default"},"plain_text":", ","href":null},{"type":"text","t'
            'ext":{"content":"Twitter (@NYTopinion)","link":{"url":"http://twit'
            'ter.com/NYTOpinion"}},"annotations":{"bold":false,"italic":true,"s'
            'trikethrough":false,"underline":false,"code":false,"color":"defaul'
            't"},"plain_text":"Twitter (@NYTopinion)","href":"http://twitter.co'
            'm/NYTOpinion"},{"type":"text","text":{"content":" and ","link":nul'
            'l},"annotations":{"bold":false,"italic":true,"strikethrough":false'
            ',"underline":false,"code":false,"color":"default"},"plain_text":" '
            'and ","href":null},{"type":"text","text":{"content":"Instagram","l'
            'ink":{"url":"https://www.instagram.com/nytopinion/"}},"annotations'
            '":{"bold":false,"italic":true,"strikethrough":false,"underline":fa'
            'lse,"code":false,"color":"default"},"plain_text":"Instagram","href'
            '":"https://www.instagram.com/nytopinion/"},{"type":"text","text":{'
            '"content":", and sign up for the ","link":null},"annotations":{"bo'
            'ld":false,"italic":true,"strikethrough":false,"underline":false,"c'
            'ode":false,"color":"default"},"plain_text":", and sign up for the '
            '","href":null},{"type":"text","text":{"content":"Opinion Today new'
            'sletter","link":{"url":"http://www.nytimes.com/newsletters/opinion'
            'today/"}},"annotations":{"bold":false,"italic":true,"strikethrough'
            '":false,"underline":false,"code":false,"color":"default"},"plain_t'
            'ext":"Opinion Today newsletter","href":"http://www.nytimes.com/new'
            'sletters/opiniontoday/"},{"type":"text","text":{"content":".","lin'
            'k":null},"annotations":{"bold":false,"italic":true,"strikethrough"'
            ':false,"underline":false,"code":false,"color":"default"},"plain_te'
            'xt":".","href":null}]}}],"next_cursor":null,"has_more":false}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Append block children
    def test_append_block_children(self):
        # Parameters for the API call
        id = '{{PAGE_ID}}'
        authorization = 'Bearer secret_t1CdN9S8yicG5eWLUOfhcWaOscVnFXns'
        notion_version = '{{NOTION_VERSION}}'
        body = None

        # Perform the API call through the SDK function
        result = self.controller.append_block_children(id, authorization, notion_version, body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['date'] = None
        expected_headers['transfer-encoding'] = None
        expected_headers['connection'] = None
        expected_headers['x-dns-prefetch-control'] = None
        expected_headers['x-frame-options'] = None
        expected_headers['strict-transport-security'] = None
        expected_headers['x-download-options'] = None
        expected_headers['x-content-type-options'] = None
        expected_headers['x-xss-protection'] = None
        expected_headers['referrer-policy'] = None
        expected_headers['content-security-policy'] = None
        expected_headers['x-content-security-policy'] = None
        expected_headers['x-webkit-csp'] = None
        expected_headers['set-cookie'] = None
        expected_headers['etag'] = None
        expected_headers['vary'] = None
        expected_headers['cf-cache-status'] = None
        expected_headers['cf-request-id'] = None
        expected_headers['expect-ct'] = None
        expected_headers['server'] = None
        expected_headers['cf-ray'] = None
        expected_headers['content-encoding'] = None
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"object":"block","id":"a1712d54-53e4-4893-a69d-4d581cd2c845","cre'
            'ated_time":"2021-04-27T20:38:19.437Z","last_edited_time":"2021-05-'
            '12T06:07:37.724Z","has_children":true,"type":"child_page","child_p'
            'age":{"title":"Who Will Teach Silicon Valley to Be Ethical? "}}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # This endpoint allows you to update block content. [See Full Documentation](https://developers.notion.com/reference/update-a-block)
    def test_update_a_block(self):
        # Parameters for the API call
        id = '{{BLOCK_ID}}'
        notion_version = '{{NOTION_VERSION}}'
        body = None

        # Perform the API call through the SDK function
        result = self.controller.update_a_block(id, notion_version, body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['date'] = None
        expected_headers['transfer-encoding'] = None
        expected_headers['connection'] = None
        expected_headers['x-dns-prefetch-control'] = None
        expected_headers['x-frame-options'] = None
        expected_headers['strict-transport-security'] = None
        expected_headers['x-download-options'] = None
        expected_headers['x-content-type-options'] = None
        expected_headers['x-xss-protection'] = None
        expected_headers['referrer-policy'] = None
        expected_headers['content-security-policy'] = None
        expected_headers['x-content-security-policy'] = None
        expected_headers['x-webkit-csp'] = None
        expected_headers['set-cookie'] = None
        expected_headers['etag'] = None
        expected_headers['vary'] = None
        expected_headers['cf-cache-status'] = None
        expected_headers['expect-ct'] = None
        expected_headers['server'] = None
        expected_headers['cf-ray'] = None
        expected_headers['content-encoding'] = None
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"object":"block","id":"4868767d-9029-4b9d-a41b-652ef4c9c7b9","cre'
            'ated_time":"2021-08-06T17:46:00.000Z","last_edited_time":"2021-08-'
            '12T00:12:00.000Z","has_children":false,"type":"paragraph","paragra'
            'ph":{"text":[{"type":"text","text":{"content":"hello to you","link'
            '":null},"annotations":{"bold":false,"italic":false,"strikethrough"'
            ':false,"underline":false,"code":false,"color":"default"},"plain_te'
            'xt":"hello to you","href":null}]}}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Retrieve a block
    def test_retrieve_a_block(self):
        # Parameters for the API call
        id = '{{BLOCK_ID}}'
        notion_version = '{{NOTION_VERSION}}'

        # Perform the API call through the SDK function
        result = self.controller.retrieve_a_block(id, notion_version)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['date'] = None
        expected_headers['transfer-encoding'] = None
        expected_headers['connection'] = None
        expected_headers['x-dns-prefetch-control'] = None
        expected_headers['x-frame-options'] = None
        expected_headers['strict-transport-security'] = None
        expected_headers['x-download-options'] = None
        expected_headers['x-content-type-options'] = None
        expected_headers['x-xss-protection'] = None
        expected_headers['referrer-policy'] = None
        expected_headers['content-security-policy'] = None
        expected_headers['x-content-security-policy'] = None
        expected_headers['x-webkit-csp'] = None
        expected_headers['set-cookie'] = None
        expected_headers['etag'] = None
        expected_headers['vary'] = None
        expected_headers['cf-cache-status'] = None
        expected_headers['expect-ct'] = None
        expected_headers['server'] = None
        expected_headers['cf-ray'] = None
        expected_headers['content-encoding'] = None
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"object":"block","id":"4868767d-9029-4b9d-a41b-652ef4c9c7b9","cre'
            'ated_time":"2021-08-06T17:46:00.000Z","last_edited_time":"2021-08-'
            '12T00:12:00.000Z","has_children":false,"type":"paragraph","paragra'
            'ph":{"text":[{"type":"text","text":{"content":"hello to you","link'
            '":null},"annotations":{"bold":false,"italic":false,"strikethrough"'
            ':false,"underline":false,"code":false,"color":"default"},"plain_te'
            'xt":"hello to you","href":null}]}}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Delete a block
    def test_delete_a_block(self):
        # Parameters for the API call
        id = '{{BLOCK_ID}}'
        notion_version = '{{NOTION_VERSION}}'

        # Perform the API call through the SDK function
        result = self.controller.delete_a_block(id, notion_version)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['date'] = None
        expected_headers['transfer-encoding'] = None
        expected_headers['connection'] = None
        expected_headers['set-cookie'] = None
        expected_headers['x-dns-prefetch-control'] = None
        expected_headers['x-frame-options'] = None
        expected_headers['strict-transport-security'] = None
        expected_headers['x-download-options'] = None
        expected_headers['x-content-type-options'] = None
        expected_headers['x-xss-protection'] = None
        expected_headers['referrer-policy'] = None
        expected_headers['content-security-policy'] = None
        expected_headers['x-content-security-policy'] = None
        expected_headers['x-webkit-csp'] = None
        expected_headers['etag'] = None
        expected_headers['vary'] = None
        expected_headers['cf-cache-status'] = None
        expected_headers['expect-ct'] = None
        expected_headers['server'] = None
        expected_headers['cf-ray'] = None
        expected_headers['content-encoding'] = None
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"object":"block","id":"4868767d-9029-4b9d-a41b-652ef4c9c7b9","cre'
            'ated_time":"2021-08-06T17:46:00.000Z","last_edited_time":"2022-02-'
            '24T22:26:00.000Z","created_by":{"object":"user","id":"6794760a-1f1'
            '5-45cd-9c65-0dfe42f5135a"},"last_edited_by":{"object":"user","id":'
            '"92a680bb-6970-4726-952b-4f4c03bff617"},"has_children":false,"arch'
            'ived":true,"type":"paragraph","paragraph":{"text":[{"type":"text",'
            '"text":{"content":"hello to you","link":null},"annotations":{"bold'
            '":false,"italic":false,"strikethrough":false,"underline":false,"co'
            'de":false,"color":"default"},"plain_text":"hello to you","href":nu'
            'll}]}}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

