# -*- coding: utf-8 -*-

"""
notionapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from notionapi.api_helper import APIHelper


class CommentsControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(CommentsControllerTests, cls).setUpClass()
        cls.controller = cls.client.comments
        cls.response_catcher = cls.controller.http_call_back

    # Retrieve a user object using the ID specified in the request path.
    def test_retrieve_comments(self):
        # Parameters for the API call
        notion_version = '{{NOTION_VERSION}}'
        block_id = '{{BLOCK_ID}}'
        page_size = 100

        # Perform the API call through the SDK function
        result = self.controller.retrieve_comments(notion_version, block_id, page_size)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-security-policy'] = None
        expected_headers['x-dns-prefetch-control'] = None
        expected_headers['x-frame-options'] = None
        expected_headers['strict-transport-security'] = None
        expected_headers['x-download-options'] = None
        expected_headers['x-content-type-options'] = None
        expected_headers['x-permitted-cross-domain-policies'] = None
        expected_headers['referrer-policy'] = None
        expected_headers['x-xss-protection'] = None
        expected_headers['content-length'] = None
        expected_headers['etag'] = None
        expected_headers['vary'] = None
        expected_headers['date'] = None
        expected_headers['connection'] = None
        expected_headers['keep-alive'] = None
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"object":"list","results":[{"object":"comment","id":"ed4c62f2-c0a'
            'd-4081-b6b8-dad025637741","parent":{"type":"block_id","block_id":"'
            '5d4ca33c-d6b7-4675-93d9-84b70af45d1c"},"discussion_id":"ce18f8c6-e'
            'f2a-427f-b416-43531fc7c117","created_time":"2022-07-15T21:38:00.00'
            '0Z","last_edited_time":"2022-07-15T21:38:00.000Z","created_by":{"o'
            'bject":"user","id":"952f41bb-da96-4d36-9c2e-74924eee8ef1"},"rich_t'
            'ext":[{"type":"text","text":{"content":"Please cite your source","'
            'link":null},"annotations":{"bold":false,"italic":false,"strikethro'
            'ugh":false,"underline":false,"code":false,"color":"default"},"plai'
            'n_text":"Please cite your source","href":null}]},{"object":"commen'
            't","id":"8949cb38-aee6-4c62-ba96-6ef7df9b4cf2","parent":{"type":"b'
            'lock_id","block_id":"5d4ca33c-d6b7-4675-93d9-84b70af45d1c"},"discu'
            'ssion_id":"e63f446f-a84a-4cab-8f5a-b9e7779ecb67","created_time":"2'
            '022-07-15T21:38:00.000Z","last_edited_time":"2022-07-15T21:38:00.0'
            '00Z","created_by":{"object":"user","id":"952f41bb-da96-4d36-9c2e-7'
            '4924eee8ef1"},"rich_text":[{"type":"text","text":{"content":"What '
            'other nutrients does kale have?","link":null},"annotations":{"bold'
            '":false,"italic":false,"strikethrough":false,"underline":false,"co'
            'de":false,"color":"default"},"plain_text":"What other nutrients do'
            'es kale have?","href":null}]},{"object":"comment","id":"6cd52483-6'
            'd55-4f8a-a724-4adb1c17ed43","parent":{"type":"block_id","block_id"'
            ':"5d4ca33c-d6b7-4675-93d9-84b70af45d1c"},"discussion_id":"ce18f8c6'
            '-ef2a-427f-b416-43531fc7c117","created_time":"2022-07-18T21:48:00.'
            '000Z","last_edited_time":"2022-07-18T21:48:00.000Z","created_by":{'
            '"object":"user","id":"e450a39e-9051-4d36-bc4e-8581611fc592"},"rich'
            '_text":[{"type":"text","text":{"content":"https://www.healthline.c'
            'om/nutrition/10-proven-benefits-of-kale","link":{"url":"https://ww'
            'w.healthline.com/nutrition/10-proven-benefits-of-kale"}},"annotati'
            'ons":{"bold":false,"italic":false,"strikethrough":false,"underline'
            '":false,"code":false,"color":"default"},"plain_text":"https://www.'
            'healthline.com/nutrition/10-proven-benefits-of-kale","href":"https'
            '://www.healthline.com/nutrition/10-proven-benefits-of-kale"}]}],"n'
            'ext_cursor":null,"has_more":false,"type":"comment","comment":{}}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Add comment to discussion
    def test_add_comment_to_discussion(self):
        # Parameters for the API call
        notion_version = '{{NOTION_VERSION}}'
        body = None

        # Perform the API call through the SDK function
        result = self.controller.add_comment_to_discussion(notion_version, body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-security-policy'] = None
        expected_headers['x-dns-prefetch-control'] = None
        expected_headers['x-frame-options'] = None
        expected_headers['strict-transport-security'] = None
        expected_headers['x-download-options'] = None
        expected_headers['x-content-type-options'] = None
        expected_headers['x-permitted-cross-domain-policies'] = None
        expected_headers['referrer-policy'] = None
        expected_headers['x-xss-protection'] = None
        expected_headers['content-length'] = None
        expected_headers['etag'] = None
        expected_headers['vary'] = None
        expected_headers['date'] = None
        expected_headers['connection'] = None
        expected_headers['keep-alive'] = None
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"object":"comment","id":"6cd52483-6d55-4f8a-a724-4adb1c17ed43","p'
            'arent":{"type":"block_id","block_id":"5d4ca33c-d6b7-4675-93d9-84b7'
            '0af45d1c"},"discussion_id":"ce18f8c6-ef2a-427f-b416-43531fc7c117",'
            '"created_time":"2022-07-18T21:48:00.000Z","last_edited_time":"2022'
            '-07-18T21:48:00.000Z","created_by":{"object":"user","id":"e450a39e'
            '-9051-4d36-bc4e-8581611fc592"},"rich_text":[{"type":"text","text":'
            '{"content":"https://www.healthline.com/nutrition/10-proven-benefit'
            's-of-kale","link":{"url":"https://www.healthline.com/nutrition/10-'
            'proven-benefits-of-kale"}},"annotations":{"bold":false,"italic":fa'
            'lse,"strikethrough":false,"underline":false,"code":false,"color":"'
            'default"},"plain_text":"https://www.healthline.com/nutrition/10-pr'
            'oven-benefits-of-kale","href":"https://www.healthline.com/nutritio'
            'n/10-proven-benefits-of-kale"}]}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

